import React, { useCallback, useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { router, useFocusEffect } from "expo-router";
import { apiGet, apiPut } from "../lib/api";
import { getProfile, setProfile } from "../lib/session";

export default function ContractScreen(){
 const [contract,setContract]=useState<any>(null);const [tenant,setTenant]=useState<any>(getProfile());const [editing,setEditing]=useState(false);const [name,setName]=useState("");const [phone,setPhone]=useState("");const [address,setAddress]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{try{const [c,p]=await Promise.all([apiGet<any>("/api/tenant/contract"),apiGet<any>("/api/tenant/me")]);setContract(c.data||null);setTenant(p.data||null);setProfile(p.data||null);setName(p.data?.name||"");setPhone(p.data?.phone||"");setAddress(p.data?.address||"");}catch(e){Alert.alert("Không tải được hợp đồng",e instanceof Error?e.message:"Lỗi API.");}finally{setLoading(false);}},[]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 const save=async()=>{setSaving(true);try{const r=await apiPut<any>("/api/tenant/me",{name,phone,address});setTenant(r.data||{...tenant,name,phone,address});setProfile(r.data||{...tenant,name,phone,address});setEditing(false);Alert.alert("Thành công","Thông tin liên hệ đã được cập nhật.");}catch(e){Alert.alert("Cập nhật thất bại",e instanceof Error?e.message:"Lỗi API.");}finally{setSaving(false)}};
 if(loading)return <SafeAreaView style={styles.safe}><ActivityIndicator size="large" color="#2563EB" style={{marginTop:80}}/></SafeAreaView>;
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}>
  <View style={styles.header}><Pressable style={styles.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={23} color="#172B4D"/></Pressable><Text style={styles.title}>Hợp đồng thuê</Text><Pressable style={styles.back} onPress={()=>setEditing(v=>!v)}><Ionicons name={editing?"close-outline":"create-outline"} size={21} color="#2563EB"/></Pressable></View>
  <View style={styles.status}><View style={styles.icon}><Ionicons name="document-text-outline" size={25} color="#2563EB"/></View><View style={{flex:1}}><Text style={styles.small}>TRẠNG THÁI</Text><Text style={styles.statusTitle}>{contract?.status||"--"}</Text><Text style={styles.small}>ID: {contract?.id||"--"}</Text></View></View>
  <Text style={styles.section}>Thông tin người thuê</Text><View style={styles.card}><Field label="Họ và tên" value={name} edit={editing} onChange={setName}/><Field label="Số điện thoại" value={phone} edit={editing} onChange={setPhone}/><Field label="Địa chỉ" value={address} edit={editing} onChange={setAddress} last/>{editing&&<Pressable style={styles.save} onPress={save} disabled={saving}><Text style={styles.saveText}>{saving?"Đang lưu...":"Lưu thay đổi"}</Text></Pressable>}</View>
  <Text style={styles.section}>Điều khoản</Text><View style={styles.card}><Row label="Phòng" value={contract?.room?.room_name||"--"}/><Row label="Ngày bắt đầu" value={contract?.start_date||"--"}/><Row label="Ngày kết thúc" value={contract?.end_date||"--"}/><Row label="Tiền thuê/tháng" value={money(contract?.monthly_rent)}/><Row label="Tiền cọc" value={money(contract?.deposit)}/><Row label="Giá điện" value={money(contract?.electricity_price)+"/kWh"}/><Row label="Phí dịch vụ" value={money(contract?.service_fee)}/></View>
 </ScrollView></SafeAreaView>
}
function Field({label,value,edit,onChange,last}:{label:string;value:string;edit:boolean;onChange:(v:string)=>void;last?:boolean}){return <View style={[styles.field,!last&&styles.fieldBorder]}><Text style={styles.small}>{label}</Text>{edit?<TextInput style={styles.input} value={value} onChangeText={onChange}/>:<Text style={styles.value}>{value||"--"}</Text>}</View>}
function Row({label,value}:{label:string;value:string}){return <View style={styles.row}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{value}</Text></View>}
function money(n?:number){return Number(n||0).toLocaleString("vi-VN")+" đ"}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#F5F7FB"},content:{padding:20,paddingBottom:40},header:{height:55,flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:14},back:{width:42,height:42,borderRadius:13,backgroundColor:"#FFF",alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:"#E2E8F0"},title:{fontSize:19,fontWeight:"800",color:"#172B4D"},status:{padding:16,borderRadius:17,backgroundColor:"#FFF",borderWidth:1,borderColor:"#E2E8F0",flexDirection:"row",gap:12,alignItems:"center"},icon:{width:50,height:50,borderRadius:15,backgroundColor:"#EFF6FF",alignItems:"center",justifyContent:"center"},small:{fontSize:10,color:"#64748B",fontWeight:"700"},statusTitle:{fontSize:16,fontWeight:"800",color:"#15803D",marginVertical:3},section:{fontSize:18,fontWeight:"800",color:"#172B4D",marginTop:22,marginBottom:10},card:{backgroundColor:"#FFF",borderRadius:16,borderWidth:1,borderColor:"#E2E8F0",paddingHorizontal:15,paddingBottom:12},field:{paddingVertical:14},fieldBorder:{borderBottomWidth:1,borderBottomColor:"#F1F5F9"},value:{fontSize:15,fontWeight:"700",color:"#172B4D",marginTop:4},input:{marginTop:4,fontSize:15,color:"#172B4D",borderBottomWidth:1,borderBottomColor:"#93C5FD",paddingVertical:4},save:{marginTop:12,borderRadius:13,backgroundColor:"#2563EB",padding:13,alignItems:"center"},saveText:{color:"#FFF",fontWeight:"800"},row:{paddingVertical:13,flexDirection:"row",justifyContent:"space-between",borderBottomWidth:1,borderBottomColor:"#F1F5F9"},rowLabel:{fontSize:13,color:"#64748B"},rowValue:{fontSize:13,fontWeight:"800",color:"#172B4D",maxWidth:"55%",textAlign:"right"}
});
