from flask import Blueprint, jsonify, request

from services.auth_service import require_landlord
from services.contract_service import (
    create_contract,
    get_all_contracts,
    get_contract_by_id,
    end_contract,
    cancel_contract
)


contracts_bp = Blueprint("contracts", __name__)


def serialize_contract(data):
    result = dict(data or {})
    for field in ["created_at", "updated_at"]:
        value = result.get(field)
        if hasattr(value, "isoformat"):
            result[field] = value.isoformat()
    return result


@contracts_bp.route("/api/contracts", methods=["POST"])
@require_landlord
def create_new_contract():
    try:
        data = request.get_json(silent=True) or {}

        if not data:
            return jsonify({
                "success": False,
                "message": "Request body is required"
            }), 400

        # room_id/tenant_id are selected from existing records by the UI;
        # the contract document ID itself is generated by Firestore.
        required_fields = ["room_id", "tenant_id", "start_date", "monthly_rent"]
        for field in required_fields:
            if data.get(field) in (None, ""):
                return jsonify({
                    "success": False,
                    "message": f"{field} is required"
                }), 400

        contract = create_contract(data)

        return jsonify({
            "success": True,
            "message": "Contract created successfully",
            "data": serialize_contract(contract)
        }), 201

    except ValueError as e:
        return jsonify({
            "success": False,
            "message": str(e)
        }), 400

    except Exception as e:
        return jsonify({
            "success": False,
            "message": str(e)
        }), 500


@contracts_bp.route("/api/contracts", methods=["GET"])
@require_landlord
def get_contracts():
    try:
        status = request.args.get("status")

        contracts = get_all_contracts(status)

        result = [
            serialize_contract(contract)
            for contract in contracts
        ]

        return jsonify({
            "success": True,
            "count": len(result),
            "data": result
        })

    except Exception as e:
        return jsonify({
            "success": False,
            "message": str(e)
        }), 500


@contracts_bp.route("/api/contracts/<contract_id>", methods=["GET"])
@require_landlord
def get_contract(contract_id):
    try:
        contract = get_contract_by_id(contract_id)

        if not contract:
            return jsonify({
                "success": False,
                "message": "Contract not found"
            }), 404

        result = serialize_contract(contract)
        db = __import__("services.firebase_service", fromlist=["get_firestore"]).get_firestore()

        tenant = None

        # Prefer the immutable tenant snapshot stored on the contract. This
        # keeps historical contract details available after tenant deletion.
        snapshot = result.get("tenant_snapshot")
        if isinstance(snapshot, dict) and snapshot.get("name"):
            tenant = dict(snapshot)
        elif result.get("tenant_id"):
            # Backward compatibility for contracts created before snapshots
            # were introduced.
            td = db.collection("tenants").document(str(result["tenant_id"])).get()
            if td.exists:
                tenant = td.to_dict() or {}
                tenant["id"] = td.id

        room = None
        if result.get("room_id"):
            rd = db.collection("rooms").document(str(result["room_id"])).get()
            if rd.exists:
                room = rd.to_dict() or {}
                room["room_id"] = rd.id

        result["tenant"] = {
            "id": tenant.get("id"),
            "name": tenant.get("name"),
            "email": tenant.get("email")
        } if tenant else None
        result["room"] = {
            "room_id": room.get("room_id"),
            "room_name": room.get("room_name")
        } if room else None

        return jsonify({
            "success": True,
            "data": result
        })

    except Exception as e:
        return jsonify({
            "success": False,
            "message": str(e)
        }), 500


@contracts_bp.route(
    "/api/contracts/<contract_id>/end",
    methods=["PATCH", "POST"]
)
@require_landlord
def end_existing_contract(contract_id):
    try:
        contract = end_contract(contract_id)

        if not contract:
            return jsonify({
                "success": False,
                "message": "Contract not found"
            }), 404

        return jsonify({
            "success": True,
            "message": "Contract ended successfully",
            "data": serialize_contract(contract)
        })

    except ValueError as e:
        return jsonify({
            "success": False,
            "message": str(e)
        }), 400

    except Exception as e:
        return jsonify({
            "success": False,
            "message": str(e)
        }), 500


@contracts_bp.route(
    "/api/contracts/<contract_id>/cancel",
    methods=["PATCH", "POST"]
)
@require_landlord
def cancel_existing_contract(contract_id):
    try:
        contract = cancel_contract(contract_id)

        if not contract:
            return jsonify({
                "success": False,
                "message": "Contract not found"
            }), 404

        return jsonify({
            "success": True,
            "message": "Contract cancelled successfully",
            "data": serialize_contract(contract)
        })

    except ValueError as e:
        return jsonify({
            "success": False,
            "message": str(e)
        }), 400

    except Exception as e:
        return jsonify({
            "success": False,
            "message": str(e)
        }), 500