from datetime import datetime, timezone

from flask import Blueprint, request, jsonify

from firebase_config import initialize_firebase
from services.settings_service import get_electricity_price
from services.auth_service import require_landlord
from services.id_service import new_document_ref


rooms_bp = Blueprint("rooms", __name__)

firestore_db, realtime_db = initialize_firebase()


def serialize_room(doc):
    """Serialize a room while always exposing its Firestore-generated ID."""
    room = doc.to_dict() or {}
    room["id"] = doc.id
    room["room_id"] = doc.id  # backward-compatible alias used by energy/RTDB APIs

    for field in ("created_at", "updated_at", "occupancy_updated_at"):
        if hasattr(room.get(field), "isoformat"):
            room[field] = room[field].isoformat()

    return room


@rooms_bp.route("/api/rooms", methods=["POST"])
@require_landlord
def create_room():
    """Create a room; room_id is generated by Firestore, never entered by admin."""
    data = request.get_json(silent=True) or {}

    room_name = (data.get("room_name") or "").strip()
    device_id = (data.get("device_id") or "").strip() or None

    if not room_name:
        return jsonify({
            "success": False,
            "message": "room_name is required"
        }), 400

    try:
        power_limit = float(data.get("power_limit", 2500))
        if power_limit <= 0:
            raise ValueError
    except (TypeError, ValueError):
        return jsonify({
            "success": False,
            "message": "power_limit must be a positive number"
        }), 400

    now = datetime.now(timezone.utc)
    room_ref = new_document_ref("rooms")
    room_data = {
        "room_name": room_name,
        "device_id": device_id,
        "status": "available",
        "occupied": False,
        "tenant_id": None,
        "person_count": 0,
        "power_limit": power_limit,
        "electricity_price": get_electricity_price(),
        "created_at": now,
        "updated_at": now,
    }

    room_ref.set(room_data)
    room = serialize_room(room_ref.get())

    return jsonify({
        "success": True,
        "message": "Room created successfully",
        "data": room
    }), 201


@rooms_bp.route("/api/rooms", methods=["GET"])
@require_landlord
def get_rooms():
    rooms = [serialize_room(doc) for doc in firestore_db.collection("rooms").stream()]

    return jsonify({
        "success": True,
        "count": len(rooms),
        "data": rooms
    })


@rooms_bp.route("/api/rooms/<room_id>", methods=["GET"])
@require_landlord
def get_room(room_id):
    """Get one room plus related tenant/active-contract information."""
    room_ref = firestore_db.collection("rooms").document(room_id)
    doc = room_ref.get()

    if not doc.exists:
        return jsonify({
            "success": False,
            "message": "Room not found"
        }), 404

    room = serialize_room(doc)
    tenant_id = room.get("tenant_id")

    tenant = None
    if tenant_id:
        tenant_doc = firestore_db.collection("tenants").document(str(tenant_id)).get()
        if tenant_doc.exists:
            tenant = tenant_doc.to_dict() or {}
            tenant["id"] = tenant_doc.id
            tenant.pop("password", None)
            tenant.pop("password_hash", None)

    contract = None
    contract_docs = (
        firestore_db.collection("contracts")
        .where("room_id", "==", room_id)
        .where("status", "==", "active")
        .limit(1)
        .stream()
    )
    for contract_doc in contract_docs:
        contract = contract_doc.to_dict() or {}
        contract["id"] = contract_doc.id
        break

    room["tenant"] = tenant
    room["active_contract"] = contract

    # Include the latest electrical snapshot so the room detail action
    # can show voltage/current/power/energy without a second client call.
    try:
        from services.firebase_service import get_realtime_db
        realtime = get_realtime_db().child("rooms").child(room_id).get() or {}
    except Exception:
        realtime = {}
    room["realtime"] = realtime

    return jsonify({
        "success": True,
        "data": room
    })


@rooms_bp.route("/api/rooms/<room_id>", methods=["PUT"])
@require_landlord
def update_room(room_id):
    data = request.get_json(silent=True) or {}
    room_ref = firestore_db.collection("rooms").document(room_id)

    if not room_ref.get().exists:
        return jsonify({
            "success": False,
            "message": "Room not found"
        }), 404

    # IDs are immutable and must never be supplied in an update payload.
    data.pop("room_id", None)
    data.pop("id", None)
    data.pop("tenant", None)
    data.pop("active_contract", None)

    if "room_name" in data:
        data["room_name"] = (data.get("room_name") or "").strip()
        if not data["room_name"]:
            return jsonify({"success": False, "message": "room_name cannot be empty"}), 400

    if "power_limit" in data:
        try:
            data["power_limit"] = float(data["power_limit"])
            if data["power_limit"] <= 0:
                raise ValueError
        except (TypeError, ValueError):
            return jsonify({"success": False, "message": "power_limit must be a positive number"}), 400

    data["updated_at"] = datetime.now(timezone.utc)
    room_ref.update(data)

    return jsonify({
        "success": True,
        "message": "Room updated successfully",
        "data": serialize_room(room_ref.get())
    })


@rooms_bp.route("/api/rooms/<room_id>", methods=["DELETE"])
@require_landlord
def delete_room(room_id):
    room_ref = firestore_db.collection("rooms").document(room_id)

    if not room_ref.get().exists:
        return jsonify({
            "success": False,
            "message": "Room not found"
        }), 404

    # Do not delete a room that still has an active contract.
    active_contract = (
        firestore_db.collection("contracts")
        .where("room_id", "==", room_id)
        .where("status", "==", "active")
        .limit(1)
        .stream()
    )
    if any(active_contract):
        return jsonify({
            "success": False,
            "message": "Cannot delete a room with an active contract"
        }), 409

    room_ref.delete()

    return jsonify({
        "success": True,
        "message": "Room deleted successfully"
    })


@rooms_bp.route("/api/rooms/<room_id>/assign-tenant", methods=["POST"])
@require_landlord
def assign_tenant_to_room(room_id):
    """Deprecated: room/tenant relationships are managed by contracts."""
    return jsonify({
        "success": False,
        "message": "Không thể gán khách trực tiếp vào phòng. Hãy tạo hoặc kết thúc hợp đồng trong mục Hợp đồng."
    }), 409
